### ISSUE TITLE
Uncaught node.js Error ( El Capitan 10.11.6 )

### ISSUE THREAD

**Issue by alfuraiji** [guerrerocarlos/TorrenTV#100]
First use of this app on my mac once I open it I got Uncaught node.js Error

El Capitan 10.11.6
Torrent TV 0.9.6

**Comment by olibd** [comment]
Same thing on my machine. Happens at launch

full error:

`Uncaught node.js Error

TypeError: Cannot read property 'documentElement' of undefined
    at Object.exports.parseStringSync (/private/var/folders/rc/sftcrnln5m3dlwdd2rbj1txw0000gn/T/.org.chromium.Chromium.b8CcIn/node_modules/airplay-js/node_modules/plist-with-patches/lib/plist.js:79:10)
    at eval (/private/var/folders/rc/sftcrnln5m3dlwdd2rbj1txw0000gn/T/.org.chromium.Chromium.b8CcIn/node_modules/airplay-js/airplay/client.js:184:25)
    at Socket.eval (/private/var/folders/rc/sftcrnln5m3dlwdd2rbj1txw0000gn/T/.org.chromium.Chromium.b8CcIn/node_modules/airplay-js/airplay/client.js:39:13)
    at Socket.EventEmitter.emit (events.js:98:17)
    at readableAddChunk (_stream_readable.js:156:16)
    at Socket.Readable.push (_stream_readable.js:123:10)
    at TCP.onread (net.js:509:20)
`

on macOS Sierra 10.12.2
TorrenTV 0.9.6

**Comment by Verbrugsken** [comment]
Same here. 
Uncaught node.js Error

TypeError: Cannot read property 'documentElement' of undefined
    at Object.exports.parseStringSync (/private/var/folders/hr/2ky4d4c947580h_4cbtp11r40000gn/T/.org.chromium.Chromium.C82yO8/node_modules/airplay-js/node_modules/plist-with-patches/lib/plist.js:79:10)
    at eval (/private/var/folders/hr/2ky4d4c947580h_4cbtp11r40000gn/T/.org.chromium.Chromium.C82yO8/node_modules/airplay-js/airplay/client.js:184:25)
    at Socket.eval (/private/var/folders/hr/2ky4d4c947580h_4cbtp11r40000gn/T/.org.chromium.Chromium.C82yO8/node_modules/airplay-js/airplay/client.js:39:13)

MacOS 10.12.3
TorrenTV 0.9.6
